import './globals.css';

<<<<<<< Updated upstream
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'
=======
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './Components/Navbar';
>>>>>>> Stashed changes

import Start from './Components/Start';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Botonetics',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< Updated upstream
        
        <Navbar/>
=======

        <Navbar />
>>>>>>> Stashed changes
        {children}
      </body>
    </html>
  );
}
