export const colors_array = [
    "#FF0000", "#FE0F00", "#FD1F00", "#FC2E00", "#FB3E00", "#FA4E00", "#F95D00", "#F86D00",
    "#F77D00", "#F68C00", "#F59C00", "#F4AB00", "#F3BB00", "#F2CB00", "#F1DA00", "#F0EA00",
    "#EFFA00", "#EEFF00", "#EE0000", "#DE0000", "#CE0000", "#BF0000", "#AF0000", "#9F0000",
    "#8F0000", "#7F0000", "#6F0000", "#5F0000", "#4F0000", "#3F0000", "#2F0000", "#1F0000",
    "#0F0000", "#0F000F", "#0F001F", "#0F002E", "#0F003E", "#0F004E", "#0F005D", "#0F006D",
    "#0F007D", "#0F008C", "#0F009C", "#0F00AB", "#0F00BB", "#0F00CB", "#0F00DA", "#0F00EA",
    "#0F00FA", "#0F00FF", "#0E00FF", "#0D00FF", "#0C00FF", "#0B00FF", "#0A00FF", "#0900FF",
    "#0800FF", "#0700FF", "#0600FF", "#0500FF", "#0400FF", "#0300FF", "#0200FF", "#0100FF",
    "#0000FF", "#0000FE", "#0000FD", "#0000FC", "#0000FB", "#0000FA", "#0000F9", "#0000F8",
    "#0000F7", "#0000F6", "#0000F5", "#0000F4", "#0000F3", "#0000F2", "#0000F1", "#0000F0"
  ];

// color pallet wise 
  export const colorPalleteWise  = [
    // Basic Colors
    "black",
    "white",
    "gray",
    "silver",
  
    // Primary Colors
    "red",
    "green",
    "blue",
  
    // Secondary Colors
    "cyan",
    "magenta",
    "yellow",
  
    // Tertiary Colors
    "orange",
    "purple",
    "teal",
  
    // Pastel Colors
    "pink",
    "lavender",
    "peachpuff",
    "lightblue",
    "lightgreen",
    "lightgray",
  
    // Neutral Colors
    "beige",
    "ivory",
    "tan",
    "wheat",
  
    // Warm Colors
    "tomato",
    "coral",
    "gold",
    "orange",
    "maroon",
    "indianred",
  
    // Cool Colors
    "aqua",
    "teal",
    "turquoise",
    "steelblue",
    "dodgerblue",
    "deepskyblue",
  
    // Bright Colors
    "hotpink",
    "lime",
    "fuchsia",
    "yellow",
    "cyan",
    "orange",
  
    // Earth Tones
    "saddlebrown",
    "olive",
    "peru",
    "sienna",
    "rosybrown",
    "sandybrown",
  
    // Grayscale Colors
    "darkgray",
    "dimgray",
    "gainsboro",
    "lightgray",
    "silver",
  
    // Vibrant Colors
    "violet",
    "crimson",
    "magenta",
    "chartreuse",
    "royalblue",
    "goldenrod",
  ];
  


  // random colors 

export  const randowColors = [
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "green",
    "greenyellow",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgreen",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "rebeccapurple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
  ];